[project]
name = "cycloid-profile"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Wolfram7539", email = "fuyagon44@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
]

[project.scripts]
cycloid-profile = "cycloid_profile.cycloid_gui:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
